### ISSUE TITLE
multiple cams

### ISSUE THREAD

**Issue by ss4sgoku** [fwestenberg/reolink#58]
hi your addon its awesome its easy to use it but i have a question hoy can i use it with 3 cams? i have 3 reolinks in my home withouth nvr, i can config 1 but i dont know how to config the other 2 please helpme, thanks

**Comment by fwestenberg** [comment]
You can just repeat the config line for each camera, like this:

```
camera:
- platform: reolink_dev
  host: 192.168.1.100
  username: admin
  password: YOUR_PASSWORD
  name: frontdoor
  stream: main
  protocol: rtmp

- platform: reolink_dev
  host: 192.168.1.101
  username: admin
  password: YOUR_PASSWORD
  name: backdoor
  stream: main
  protocol: rtmp
```
