### ISSUE TITLE
Cannot use services in automations or scripts

### ISSUE THREAD

**Issue by nick2k3** [fwestenberg/reolink#67]
Hi, I am having some issues triggering the services exposed by the component via automation or Scripts.

I can correctly call a service by using the Developer tool of HA or by linking to a lovelace card.

I cannot call a service by setting as the action of an automation or by inserting it into a script.:
<img width="600" alt="Schermata 2020-09-03 alle 18 07 41" src="https://user-images.githubusercontent.com/42848864/92139708-6a634700-ee10-11ea-83f4-d3eb26db3b35.png">

I get the following error:

```
2020-09-03 17:59:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2734821464] unhashable type: 'list'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1308, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1343, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 212, in service_handler
    await script_entity.async_turn_on(
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 313, in async_turn_on
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 802, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 183, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 191, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 380, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1308, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1347, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/reolink_dev/camera.py", line 86, in handler_disable_ftp
    entity = component.get_entity(call.data.get(ATTR_ENTITY_ID))
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 99, in get_entity
    entity_obj = platform.entities.get(entity_id)
TypeError: unhashable type: 'list'
```

The result does not change if I use any of the other exposed services.

Looks like this line:
File "/config/custom_components/reolink_dev/camera.py", line 86, in handler_disable_ftp
    entity = component.get_entity(call.data.get(ATTR_ENTITY_ID))
when called by lovelace or by the Developer tool, receives an object, while if called by automation or script receives a list.

Not being able to call services by automation is a nuisance as it would be great to enable motion detection and recording only when I leave home .
Does anyone have an idea on how to fix it?

**Comment by nick2k3** [comment]
Some weeks ago I tried to ask on the #devs_core discord channel, here is the dump of the discussion, although I am not sure I would be able to change the component so radically.

https://discordapp.com/channels/330944238910963714/330990195199442944/736959561386164304

> **Nick86-126/07/2020**
> hi everyone
> i'm trying to debug some issues in a custom component i'm contributing to and I think something might have broken since the latest update. In particular I am having issues to trigger a service defined in the custom component
> if I trigger it from the Developer tools everything goes ok
> if I trigger it from an automation I get an error:
> `TypeError: unhashable type: 'list'`
> 
> the service is registered in this way:
>  
> ```
> Event enable FTP
>     def handler_enable_ftp(call):
>         component = hass.data.get(DOMAIN)
>         entity = component.get_entity(call.data.get(ATTR_ENTITY_ID))        
>         if entity:
>             entity.enable_ftp_upload()
>     hass.services.async_register(DOMAIN, SERVICE_ENABLE_FTP, handler_enable_ftp)
> ```
> i tracked it down to the ServiceCall thread passing the entity ID in two different ways:
> `<ServiceCall camera.enable_ftp (c:e0f97597414447b7915670c5efff503a): entity_id=camera.reolink_e1> `--> triggered by Developer tools
>` <ServiceCall camera.enable_ftp (c:a4a33fb395b048ebbae61100f5886b63): entity_id=['camera.reolink_e1']> `-->triggered by automation
> so the `Entity_component` is actually right to complain that he's receiving a list instead of a string
> any hints on what we're doing wrong?

> **amelchio🔹26/07/2020**
> @Nick86-1 What does SERVICE_ENABLE_FTP look like?

> **Nick86-126/07/2020**
> SERVICE_ENABLE_FTP = 'enable_ftp'
> the full code is here https://github.com/fwestenberg/reolink/blob/dcde6d7fd32a1237cd5503c524bb043c28f8d4f2/custom_components/reolink_dev/camera.py#L81

> **amelchio🔹26/07/2020**
> Oh, sorry ... I thought that was a schema, my bad.
> You can use the make_entity_service_schema() and async_register_entity_service() helpers to register a service that automatically calls a method on the entity.

> **Nick86-126/07/2020**
> but why is there  a difference between a call from the developer tool and the script section of the automation?

> **amelchio🔹26/07/2020**
> Maybe you create a string in one case and a list in the other, or there is some default conversion that I don't know about.

> **Nick86-126/07/2020**
> it worked in 112, i'm looking at the diffs to check for some hint

> **Nick86-126/07/2020**
> is there any documentation on how to use make_entity_service_schema?
> I mean, can I just create an empty schema with 
> schema=make_entity_service_schema({})
>  ?

> **amelchio🔹26/07/2020**
> Yes you can.

> **Nick86-126/07/2020**
> ok I managed to create a schema but I am having trouble understanding how to use async_register_entity_service
> should i call it on a platform or a component?

> **amelchio🔹26/07/2020**
> You can do it in your setup function, looks like harmony/remote.py has a fairly simple example.

**Comment by fwestenberg** [comment]
This works for me:

![image](https://user-images.githubusercontent.com/47930023/94547723-f4f06800-024f-11eb-900e-cb3739cbff93.png)

**Comment by nick2k3** [comment]
Hi, unfortunately not, I have the same exact errors of before.

![immagine](https://user-images.githubusercontent.com/42848864/94824272-1c3c6600-0405-11eb-967a-363936f40ce7.png)
![immagine](https://user-images.githubusercontent.com/42848864/94824331-3118f980-0405-11eb-9c34-d6b11023237e.png)

I am running Home Assistant 0.115.6.

**Comment by fwestenberg** [comment]
Are you sure the service is working at all? This should work... ;-)

**Comment by nick2k3** [comment]
Sorry just had the time to re-test this.
I have removed the integration and re-added it. At the time of writing I am using Home Assistant 0.116.4.

The services do work if I call them from developer tool or through the switches defined in the yaml and used in the Lovelace card.
Here is the sequence of tests I do:
<img width="500" alt="Schermata 2020-10-28 alle 19 58 23" src="https://user-images.githubusercontent.com/42848864/97483853-4461ab00-1958-11eb-9b62-3cf396376ce9.png">
If I call it through the Developer tool:
<img width="300" alt="Schermata 2020-10-28 alle 20 02 40" src="https://user-images.githubusercontent.com/42848864/97484073-8c80cd80-1958-11eb-996c-a886893bf9d8.png">
resulting in:
<img width="500" alt="Schermata 2020-10-28 alle 20 03 20" src="https://user-images.githubusercontent.com/42848864/97484215-c225b680-1958-11eb-8002-78bccae3ed32.png">

But If I call it through a script or automation:
<img width="300" alt="Schermata 2020-10-28 alle 20 06 25" src="https://user-images.githubusercontent.com/42848864/97484525-16309b00-1959-11eb-927d-ee24c4e56c3b.png">

I get this error: 
<img width="467" alt="Schermata 2020-10-28 alle 20 07 13" src="https://user-images.githubusercontent.com/42848864/97484581-2ea0b580-1959-11eb-84a1-8fdd3e8deb9b.png">


I don't know if this might be related, but heres the extract from my yaml:

```
camera:
- platform: reolink_dev
  host: 192.168.178.25
  username: !secret reolink_username
  password: !secret reolink_password 
  name: reolink_e1
  stream: sub
  protocol: rtsp
  scan_interval: 5

binary_sensor:
  - platform: template
    sensors:
      movimento_soggiorno:
        friendly_name: "Movimento soggiorno"
        device_class: motion
        #entity_id: camera.reolink_e1
        value_template: "{{ is_state('camera.reolink_e1', 'motion') }}"
        delay_off: 
          seconds: 5
switch:
  - platform: template
    switches:
      camera_ftp:
        value_template: "{{ is_state_attr('camera.reolink_e1', 'ftp_enabled', true) }}"
        turn_on:
          service: camera.enable_ftp
          data:
            entity_id: camera.reolink_e1
        turn_off:
          service: camera.disable_ftp
          data:
            entity_id: camera.reolink_e1
        icon_template: >-
          {% if is_state_attr('camera.reolink_e1', 'ftp_enabled', true) %}
            mdi:filmstrip
          {% else %}
            mdi:filmstrip-off
          {% endif %}
      camera_ir_lights:
        value_template: "{{ is_state_attr('camera.reolink_e1', 'ir_lights_enabled', true) }}"
        turn_on:
          service: camera.enable_ir_lights
          data:
            entity_id: camera.reolink_e1
        turn_off:
          service: camera.disable_ir_lights
          data:
            entity_id: camera.reolink_e1
        icon_template: >-
          {% if is_state_attr('camera.reolink_e1', 'ir_lights_enabled', true) %}
            mdi:flashlight
          {% else %}
            mdi:flashlight-off
          {% endif %}
      camera_motion_detection:
        value_template: "{{ is_state_attr('camera.reolink_e1', 'motion_detection_enabled', true) }}"
        turn_on:
          service: camera.enable_motion_detection
          data:
            entity_id: camera.reolink_e1
        turn_off:
          service: camera.disable_motion_detection
          data:
            entity_id: camera.reolink_e1
        icon_template: >-
          {% if is_state_attr('camera.reolink_e1', 'motion_detection_enabled', true) %}
            mdi:motion-sensor
          {% else %}
            mdi:motion-sensor-off
          {% endif %}
      camera_recording:
        value_template: "{{ is_state_attr('camera.reolink_e1', 'recording_enabled', true) }}"
        turn_on:
          service: camera.enable_recording
          data:
            entity_id: camera.reolink_e1
        turn_off:
          service: camera.disable_recording
          data:
            entity_id: camera.reolink_e1
        icon_template: >-
          {% if is_state_attr('camera.reolink_e1', 'recording_enable', true) %}
            mdi:movie-roll
          {% else %}
            mdi:movie-outline
          {% endif %}
```

I am using the latest integration through HASS:
<img width="400" alt="Schermata 2020-10-28 alle 20 19 29" src="https://user-images.githubusercontent.com/42848864/97485914-0ade6f00-195b-11eb-94b8-a88eeffd536b.png">

I am not sure what else I can try short than reinstalling Home assistant from scratch and checking if it works..
